services:
  - type: web
    name: ameer-enterprises
    runtime: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_APPS_SCRIPT_URL
        sync: false
      - key: PORT
        value: 3000
